# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e498d415fb06004c20818a8efbcd353677ec02faacf53d043786dbadfa2ff6e06265e501b42ce5a23d5048761f543d5154f872eb04c4467dda6184e6f710bf68

test:
  secret_key_base: 3f363ef8d8732a03f953f07ba0e1fff71dd6675ece063cd965d50eed3eb6ef5bc3dd0c0e804205650a82171fb52a06385ca28c03dc61f6fa9ac435226de4aba5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
